[package]
name = "bevy_fps"
version = "0.1.0"
authors = ["Twinf0x <bastian.7741@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4"
kurinji = "*"